name: TypeScript Test
on:
  push:
    branches: ["main"]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo Directory
        uses: actions/checkout@v2
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.0"
      - name: NPM ci and cacheing
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
  unittest:
    name: Run UnitTest
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo Directory
        uses: actions/checkout@v2
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.0"
      - name: Get Cache Node Module
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: run unit test
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ github.workspace }}/coverage
